#!/usr/bin/env bash

COLOR_WHITE=$(tput setaf 7);
COLOR_MAGENTA=$(tput setaf 5);
FONT_BOLD=$(tput bold);
FONT_NORMAL=$(tput sgr0);

echo
echo -e "$COLOR_WHITE $FONT_BOLD Polkadot-JS Apps Setup...$FONT_NORMAL";
echo
echo -e "    Usage: polkadot-js-apps-new";
echo
echo -e "  $COLOR_MAGENTA $FONT_BOLD Cloning Polkadot-JS Apps...$COLOR_WHITE $FONT_NORMAL";
echo
git clone https://github.com/polkadot-js/apps --branch master;
cd apps;
yarn; 
yarn run build;
echo -e "    Run Polkadot-JS Apps with the command 'yarn start'";
