#!/usr/bin/env bash

name=$1

if [[ "$name" == "" || "$name" == "-"* ]]
then
  echo "  Usage: polkadot-js-apps-new <NAME>"
  echo
  exit 1
fi

lname="$(echo $name | tr '[:upper:]' '[:lower:]')"
dirname="${lname// /-}"

if [ -d "$dirname" ]; then
  echo "  Directory '$name' already exists!"
  echo
  exit 1
fi

git clone https://github.com/polkadot-js/apps.git $dirname
