#!/usr/bin/env bash

name=$1

if [[ "$name" == "" || "$name" == "-"* ]]
then
  echo "  Usage: substrate-ui-new <NAME>"
  echo
  exit 1
fi

lname="$(echo $name | tr '[:upper:]' '[:lower:]')"
dirname="${lname// /-}"

if [ -d "$dirname" ]; then
  echo "  Directory '$name' already exists!"
  echo
  exit 1
fi

git clone --branch=substrate-package https://github.com/substrate-developer-hub/substrate-ui-template.git $dirname
