#!/usr/bin/env bash

name=$1
shift
author=$1
shift

if [[ "$name" == "" || "$name" == "-"* ]]
then
  echo "Usage: substrate-node-new <NAME> <AUTHOR>"
  exit 1
fi
if [[ "$author" == "" || "$author" == "-"* ]]
then
  echo "Usage: substrate-node-new <NAME> <AUTHOR>"
  exit 1
fi

lname="$(echo $name | tr '[:upper:]' '[:lower:]')"
dirname="${lname/ /-}"

bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}Cloning project...${normal}"
if ! git clone -q https://github.com/paritytech/substrate-node-template $dirname
then
	exit 1
fi

pushd $dirname >/dev/null
rm -rf .git

echo "${bold}Customising project...${normal}"
function replace {
	find_this="$1"
	shift
	replace_with="$1"
	shift
	IFS=$'\n'
	for item in `find . -type f`
	do
		sed -i '' "s/$find_this/$replace_with/g" "$item"
	done
}
replace "Template Node" "${name}"
replace template-node "${lname/[_ ]/-}"
replace template_node "${lname/[- ]/_}"
replace Anonymous "$author"

echo "${bold}Initialising Git repo...${normal}"
git init 2>/dev/null >/dev/null
git add * .gitignore 2>/dev/null >/dev/null
git commit -a -m "Initial clone from template node" 2>/dev/null >/dev/null

echo "${bold}Initialising Webassembly build environment...${normal}"
./init.sh 2>/dev/null >/dev/null

./build.sh

echo "${bold}Building node...${normal}"
cargo build --release

echo "${bold}Done!${normal}"
popd >/dev/null
